# Generated by Django 2.0.3 on 2018-04-27 16:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='reserve',
            name='datework',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reserve',
            name='image',
            field=models.ImageField(null=True, upload_to='slip'),
        ),
        migrations.AddField(
            model_name='reserve',
            name='size',
            field=models.CharField(choices=[('less25', 'Less25'), ('between', 'Between'), ('morethan', 'Morethan')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reserve',
            name='typearea',
            field=models.CharField(choices=[('home', 'Home'), ('condo', 'Condo')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='money',
            name='reserve_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Reserve'),
        ),
    ]
