# Generated by Django 2.0.3 on 2018-04-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
