# Generated by Django 2.0.3 on 2018-04-29 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0005_auto_20180429_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='reserve',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
