# Generated by Django 2.0.3 on 2018-05-02 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20180502_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
