# Generated by Django 2.0.3 on 2018-05-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20180505_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maid',
            old_name='image',
            new_name='image_maid',
        ),
    ]
