# Generated by Django 2.0.3 on 2018-05-10 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_auto_20180508_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='postcode',
        ),
        migrations.AddField(
            model_name='reserve',
            name='addresswork',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
