# Generated by Django 2.0.3 on 2018-05-13 15:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_auto_20180510_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='money',
            name='reserve_id',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='image',
        ),
        migrations.AddField(
            model_name='money',
            name='img_slip',
            field=models.ImageField(null=True, upload_to='slip'),
        ),
        migrations.AddField(
            model_name='money',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='money',
            name='resever_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Reserve'),
        ),
        migrations.AddField(
            model_name='money',
            name='timesection',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
