# Generated by Django 2.0.3 on 2018-05-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0027_maid_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maid',
            name='email',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='maid',
            name='postcode',
        ),
    ]
