# Generated by Django 2.0.3 on 2018-05-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_auto_20180514_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maid',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maid',
            name='telephone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
