# Generated by Django 2.0.3 on 2018-05-14 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_auto_20180514_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maid',
            name='telephone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
