# Generated by Django 2.0.3 on 2018-05-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0031_auto_20180514_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maid',
            name='image_maid',
            field=models.FileField(null=True, upload_to='picmaid'),
        ),
    ]
