# Generated by Django 2.0.3 on 2018-05-14 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_auto_20180514_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
            ],
        ),
        migrations.AlterField(
            model_name='maid',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maid',
            name='image_maid',
            field=models.ImageField(blank=True, null=True, upload_to='picmaid'),
        ),
        migrations.AlterField(
            model_name='maid',
            name='telephone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='maid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.Maid'),
        ),
    ]
